name: lint_python
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  lint_python:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]    # [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.x]  # [2.7, 3.6, 3.7, 3.8, 3.9,  '3.10',  3.11, pypy39]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install black codespell flake8 isort pytest
      - run: black --check . || true
      # - run: black --diff . || true
      # - if: matrix.python-version >= 3.6
      #  run: |
      #    pip install black
      #    black --check . || true
      - run: codespell --ignore-words-list="blok" --skip="./.*"
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: isort --profile black --recursive . || true
      - run: pip install -r requirements.txt || true
      - run: pytest . || true
