# https://pre-commit.com
# https://github.com/pre-commit/action
# This GitHub Action assumes that the repo contains a valid .pre-commit-config.yaml file.
# Using pre-commit.ci is even better that using GitHub Actions for pre-commit.
name: pre-commit
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.1
